import { test } from "node:test";
import assert from "node:assert/strict";
import { analyze } from "../src/index.js";
import { fixture } from "./helpers.js";

test("full pipeline on claude export produces a golden context doc", () => {
  const result = analyze(fixture("claude-export.json"));
  assert.ok(!result.error);
  const md = result.markdown;

  // sections present
  assert.ok(md.includes("# Context: Build a tiny RSS reader"));
  assert.ok(md.includes("## Goal"));
  assert.ok(md.includes("## Current state"));
  assert.ok(md.includes("## Key topics"));
  assert.ok(md.includes("## Requirements"));
  assert.ok(md.includes("## Decisions"));
  assert.ok(md.includes("## Most representative sentences"));
  assert.ok(md.includes("## Code"));
  assert.ok(md.includes("## Commands"));
  assert.ok(md.includes("## Tech stack"));
  assert.ok(md.includes("## Action items"));
  assert.ok(md.includes("## Compressed transcript"));
  assert.ok(md.includes("## Stats"));
  assert.ok(md.includes("Auto-generated by sigil"));

  // evidence annotations
  assert.ok(/turn \d/.test(md));

  // evidence labels are human-readable, never raw regex literals
  assert.ok(!md.includes("(?:prefer"));

  // key topics are prose, not tokenized code blobs
  assert.ok(md.includes("## Key topics"));

  // code preserved (schema + worker)
  assert.ok(md.includes("```prisma"));
  assert.ok(md.includes("datasource db"));
  assert.ok(md.includes("fetchFeeds"));

  // file paths linked
  assert.ok(md.includes("prisma/schema.prisma"));

  // commands extracted
  assert.ok(md.includes("npx prisma migrate dev"));

  // compression invariant: user turns survive
  assert.ok(md.includes("It must store feed URLs in SQLite"));
});

test("distills assistant prose and keeps the user's asks", () => {
  const input = fixture("claude-export.json");
  const result = analyze(input);
  const stats = result.sections.stats;

  // core promise: assistant prose gets distilled to under half its raw length
  const assistantRetained = result.sections.transcript
    .filter((t) => t.role === "assistant")
    .reduce((n, t) => n + t.text.length, 0);
  const ratio = assistantRetained / stats.assistantChars;
  assert.ok(ratio < 0.5, `expected assistant prose distilled <50%, got ${ratio.toFixed(2)}`);

  // user asks survive verbatim
  assert.ok(result.markdown.includes("It must store feed URLs in SQLite"));

  // whole doc stays bounded (no accidental blowup)
  assert.ok(result.markdown.length < input.length * 3);
});

test("RAKE topics and transcript are deterministic across runs", () => {
  const a = analyze(fixture("claude-export.json"));
  const b = analyze(fixture("claude-export.json"));
  assert.equal(a.markdown, b.markdown);
});

test("gemini console export renders too", () => {
  const result = analyze(fixture("gemini-console.json"));
  assert.ok(!result.error);
  assert.ok(result.markdown.includes("## Decisions"));
  assert.ok(result.markdown.includes("```dockerfile"));
});

test("transcript text renders", () => {
  const result = analyze(fixture("transcript.md"));
  assert.ok(!result.error);
  assert.ok(result.markdown.includes("## Compressed transcript"));
});

test("error surfaces for garbage input", () => {
  const result = analyze("{ not valid json");
  assert.ok(result.error);
});

test("analyze exposes structured sections (evidence tree)", () => {
  const result = analyze(fixture("claude-export.json"));
  assert.ok(result.sections);
  assert.ok(Array.isArray(result.sections.keyPhrases));
  assert.ok(Array.isArray(result.sections.code));
  assert.ok(typeof result.sections.stats.tokens === "number");
  assert.ok(Array.isArray(result.sections.transcript));
  assert.ok(result.sections.representative.every((r) => typeof r.score === "number"));
});