const HONESTY_NOTE =
  "Auto-generated by sigil — deterministic heuristics and classical NLP only. " +
  "No AI model, no network, no keys. Snippets are heuristic picks; verify important claims against the original chat.";

/** Render the full evidence-annotated context document. */
export function renderContext({ chat, sections, opts = {} }) {
  const { messageCount, tokens, chars } = sections.stats;

  const sourceLabel = {
    claude: "Claude export",
    "gemini-takeout": "Google Takeout (My Activity)",
    gemini: "Gemini export",
    transcript: "pasted transcript",
    text: "pasted text (no role markers)",
    generic: "message list",
    unknown: "unknown source",
  }[chat.source] || chat.source;

  const L = [];
  const title = chat.title || "Untitled conversation";

  L.push(`# Context: ${title}`);
  L.push("");
  L.push(`- **Source:** ${sourceLabel}${chat.at ? ` · ${fmtDate(chat.at)}` : ""}`);
  L.push(`- **Conversation:** ${messageCount} messages${chat.models.length ? ` · models: ${chat.models.join(", ")}` : ""}`);
  L.push(`- **Input tokens (est):** ~${tokens} (${chars.toLocaleString()} chars)`);
  if (opts.note) L.push(`- **Note:** ${opts.note}`);
  L.push("");

  // 1 ─ Goal
  if (sections.goal) {
    L.push("## Goal");
    L.push("");
    L.push(sections.goal.text);
    L.push("");
    L.push(`_Evidence: ${secEv(sections.goal.evidence)}_`);
    L.push("");
  }

  // 2 ─ Current state (where it left off — from the final turns)
  if (sections.currentState && (sections.currentState.lastAsk || sections.currentState.nextSteps.length)) {
    L.push("## Current state");
    L.push("");
    if (sections.currentState.lastAsk) {
      L.push(`**Last ask** (user · turn ${sections.currentState.lastAsk.turn}): "${sections.currentState.lastAsk.text}"`);
      L.push("");
    }
    if (sections.currentState.nextSteps.length) {
      L.push(`**Next steps** (final assistant turns):`);
      L.push("");
      sections.currentState.nextSteps.forEach((s, i) => {
        L.push(`${i + 1}. ${s.text}`);
        L.push(`   _${s.rule} (turn ${s.turn})_`);
      });
      L.push("");
    }
  }

  // 3 ─ Key topics (RAKE)
  if (sections.keyPhrases && sections.keyPhrases.length) {
    L.push("## Key topics (RAKE, unsupervised)");
    L.push("");
    const top = sections.keyPhrases.slice(0, 8);
    L.push(...top.map(kp => `- \`${kp.phrase}\` — RAKE ${kp.score}`));
    L.push("");
  }

  // 3 ─ Requirements
  if (sections.rules.requirements.length) {
    L.push("## Requirements");
    L.push("");
    for (const r of sections.rules.requirements) pushItem(L, r);
    L.push("");
  }

  // 4 ─ Decisions
  if (sections.rules.decisions.length) {
    L.push("## Decisions");
    L.push("");
    for (const d of sections.rules.decisions) pushItem(L, d);
    L.push("");
  }

  // 5 ─ Representative sentences (TextRank + MMR)
  if (sections.representative.length) {
    L.push("## Most representative sentences");
    L.push("");
    L.push(`_Ranked by TextRank centrality, de-duplicated by MMR._`);
    L.push("");
    sections.representative.forEach((r, i) => {
      L.push(`${i + 1}. "${r.text}"`);
      L.push(`   — centrality ${r.score}, linked to ${r.links} other sentences · MMR pick #${r.mmrRank} · turn ${r.turn}`);
    });
    L.push("");
  }

  // 6 ─ Code & files
  if (sections.code.length) {
    L.push("## Code");
    L.push("");
    for (const b of sections.code) {
      const pathBit = b.path ? ` · \`${b.path}\`` : "";
      const iterBit = b.count > 1 ? ` · ${b.count} versions (final at turn ${b.turn})` : ` · turn ${b.turn}`;
      L.push(`### \`${b.lang || "text"}\` — ${b.lines} lines${pathBit}${iterBit}`);
      L.push("");
      L.push("```" + b.lang);
      L.push(b.code.replace(/\n+$/, ""));
      L.push("```");
      L.push("");
    }
  }

  // 7 ─ Files paths
  if (sections.files.length) {
    L.push("## Files mentioned");
    L.push("");
    L.push("| Path | # mentions | turns |");
    L.push("|---|---|---|");
    for (const f of sections.files.slice(0, 25)) {
      L.push(`| \`${mdEsc(f.path)}\` | ${f.count} | ${f.turns.join(", ")} |`);
    }
    L.push("");
  }

  // 8 ─ Commands
  if (sections.commands.length) {
    L.push("## Commands");
    L.push("");
    for (const c of sections.commands) L.push(`- \`${c.cmd}\` _(turn ${c.turn})_`);
    L.push("");
  }

  // 9 ─ Tech stack
  if (sections.stack.length) {
    L.push("## Tech stack");
    L.push("");
    for (const s of sections.stack.slice(0, 20)) {
      L.push(`- **${s.term}** — ${s.count}× (turns ${s.turns.join(", ")})`);
    }
    L.push("");
  }

  // 10 ─ Glossary
  if (sections.glossary.length) {
    L.push("## Terms");
    L.push("");
    for (const g of sections.glossary.slice(0, 20)) {
      L.push(`- **${g.term}**: ${g.def} _(turn ${g.turn})_`);
    }
    L.push("");
  }

  // 11 ─ Action items
  if (sections.rules.actions.length) {
    L.push("## Action items");
    L.push("");
    for (const a of sections.rules.actions) pushItem(L, a);
    L.push("");
  }

  // 12 ─ Open questions
  if (sections.questions.length) {
    L.push("## Open questions");
    L.push("");
    for (const q of sections.questions) {
      L.push(`- ${mdEsc(q.text)}`);
      L.push(`  _${q.rule} (turn ${q.turn})_`);
    }
    L.push("");
  }

  // 13 ─ Requests (user asks that are still open-ended)
  if (sections.rules.requests.length) {
    L.push("## User requests");
    L.push("");
    for (const r of sections.rules.requests) pushItem(L, r);
    L.push("");
  }

  // 15 ─ Conversation topics + compressed transcript
  L.push("## Compressed transcript");
  L.push("");
  L.push(`_User turns preserved verbatim; assistant turns keep their highest-centrality sentences. Full code lives in ## Code above._`);
  L.push("");

  // topic markers
  const topicHeaders = new Set();
  if (sections.topics.length > 1) {
    for (const seg of sections.topics) {
      if (seg.label) topicHeaders.add(seg.label);
    }
  }

  sections.transcript.forEach((t, idx) => {
    const seg = sections.topics.find(s => s.start === idx && s.start > 0);
    if (seg) {
      L.push(`> **Topic:** ${seg.label ? `\`${seg.label}\`` : `turns ${seg.start}-${seg.end}`} (turns ${seg.start}-${seg.end})`);
      L.push("");
    }
    const who = t.role === "user" ? "**You**" : "**Assistant**";
    L.push(`### ${who} — turn ${t.turn}`);
    L.push("");
    if (t.text) {
      L.push(escapeHeadings(t.text));
      L.push("");
    }
    for (const b of t.code) {
      L.push(`> [code block · \`${b.lang || "text"}\`${b.path ? ` · \`${b.path}\`` : ""} — full source in ## Code]`);
      L.push("");
    }
  });

  // ─ stats
  L.push("## Stats");
  L.push("");
  L.push(`- Input: ${sections.stats.messageCount} messages, ${sections.stats.userCount} user / ${sections.stats.assistantCount} assistant, ~${sections.stats.tokens} tokens (est.)`);
  L.push(`- Output: this document is ${(chars ? Math.round((markdownLen(L) / chars) * 100) : 0)}% of input length`);
  L.push("");
  L.push("---");
  L.push("");
  L.push(`*${HONESTY_NOTE}*`);
  L.push("");

  return L.join("\n");
}

function markdownLen(lines) {
  return lines.join("\n").length;
}

function pushItem(L, item, prefix = "- ") {
  L.push(`${prefix}${item.text}`);
  L.push(`  _${item.rule} (turn ${item.turn})_`);
}

function secEv(evidence) {
  if (!evidence || !evidence.length) return "—";
  return evidence.map(e => `${e.rule} (turn ${e.turn})`).join("; ");
}

function fmtDate(at) {
  if (!at) return "";
  const d = new Date(at);
  if (Number.isNaN(d.getTime())) return String(at).slice(0, 10);
  return d.toISOString().slice(0, 10);
}

function mdEsc(s) {
  return String(s).replace(/\|/g, "\\|");
}

// Transcript text is quoted verbatim inside a "### turn" section; any line
// that looks like a markdown heading would otherwise create a fake section.
function escapeHeadings(text) {
  return String(text).replace(/^#{1,6}\s*/gm, "\\$&");
}